In [1]:
# Importing Libraries
from tqdm.notebook import trange, tqdm
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [2]:
#Inspect the data frame
#Index on the left does not have a name and everything is off to the right.
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
431969,Data Scientist,Chief Data Science and Data Engineering Office...,"Charleroi, Belgium",via BeBee Belgique,Part-time,False,Belgium,2023-06-15 16:55:28,False,False,Belgium,None,NaN,NaN,EliteRecruitmentGroup,['aws'],{'cloud': ['aws']}
774096,Senior Data Engineer,Senior Data Engineer,"Sydney NSW, Australia",via BeBee Australia,Full-time,False,Australia,2023-08-18 01:12:28,True,False,Australia,None,NaN,NaN,Paxus,"['sql', 'snowflake', 'flow', 'git']","{'cloud': ['snowflake'], 'other': ['flow', 'gi..."
467204,Data Engineer,Data Engineer,"Dallas, TX",via Dice,Contractor,False,Sudan,2023-11-21 15:43:24,False,False,Sudan,None,NaN,NaN,Raas Infotek LLC,"['python', 'java', 'scala', 'aws', 'spark', 'k...","{'cloud': ['aws'], 'libraries': ['spark', 'kaf..."
664024,Data Analyst,Data Analytics Apprenticeship (Undergraduate),"Dallas, TX",via ZipRecruiter,Full-time,False,"Texas, United States",2023-05-02 10:02:36,False,False,United States,None,NaN,NaN,Lockton Companies,"['sas', 'sas', 'r', 'python', 'tableau', 'exce...","{'analyst_tools': ['sas', 'tableau', 'excel', ..."
421136,Business Analyst,Strategy and Performance Analyst (m/f/d),Anywhere,via LinkedIn Luxembourg,Full-time,True,Luxembourg,2023-02-28 17:02:59,False,False,Luxembourg,None,NaN,NaN,bp,['excel'],{'analyst_tools': ['excel']}

In [3]:
#Check the index
df.index

RangeIndex(start=0, stop=785741, step=1)

In [4]:
#Check the name of the index and name it
df.index.name = "job_index"

In [5]:
#Check if the name saved
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [6]:
#Attritubes data type
df.index.dtype

dtype('int64')

In [11]:
#Reset_index()
#Filtering the df for USA jobs

df_usa = df[df['job_country']== 'South Africa']

In [14]:
#Check the data frame. There are missing rows in the job index, since we filtered by country
df_usa.head()

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,138,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,None,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ..."
1,256,Data Analyst,Data Analyst,"Cape Town, South Africa",via Indeed,Full-time,False,South Africa,2023-09-06 13:08:51,True,False,South Africa,None,NaN,NaN,Mass Staffing Projects,['sql'],{'programming': ['sql']}
2,354,Cloud Engineer,Server Engineer,"Cape Town, South Africa",via LinkedIn,Full-time,False,South Africa,2023-09-22 13:43:18,False,False,South Africa,None,NaN,NaN,First Quantum Minerals,['azure'],{'cloud': ['azure']}
3,365,Data Scientist,Head of Data Science at Hire Resolve,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-01-21 13:32:58,False,False,South Africa,None,NaN,NaN,Hire Resolve,['c'],{'programming': ['c']}
4,423,Data Engineer,Data Engineer - Software Development Industry ...,"Cape Town, South Africa (+1 other)",via Pnet,Full-time,False,South Africa,2023-12-01 13:19:05,False,False,South Africa,None,NaN,NaN,Talent Candey,"['sql', 'aws', 'databricks', 'azure', 'hadoop'...","{'analyst_tools': ['ssis'], 'cloud': ['aws', '..."

# Correct the index step flow using reset_index method

In [13]:

df_usa.reset_index(inplace=True)
df_usa

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,138,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,None,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ..."
1,256,Data Analyst,Data Analyst,"Cape Town, South Africa",via Indeed,Full-time,False,South Africa,2023-09-06 13:08:51,True,False,South Africa,None,NaN,NaN,Mass Staffing Projects,['sql'],{'programming': ['sql']}
2,354,Cloud Engineer,Server Engineer,"Cape Town, South Africa",via LinkedIn,Full-time,False,South Africa,2023-09-22 13:43:18,False,False,South Africa,None,NaN,NaN,First Quantum Minerals,['azure'],{'cloud': ['azure']}
3,365,Data Scientist,Head of Data Science at Hire Resolve,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-01-21 13:32:58,False,False,South Africa,None,NaN,NaN,Hire Resolve,['c'],{'programming': ['c']}
4,423,Data Engineer,Data Engineer - Software Development Industry ...,"Cape Town, South Africa (+1 other)",via Pnet,Full-time,False,South Africa,2023-12-01 13:19:05,False,False,South Africa,None,NaN,NaN,Talent Candey,"['sql', 'aws', 'databricks', 'azure', 'hadoop'...","{'analyst_tools': ['ssis'], 'cloud': ['aws', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12409,784842,Data Analyst,Business Data Analyst,South Africa,via LinkedIn,Contractor,False,South Africa,2023-01-17 07:02:38,False,False,South Africa,None,NaN,NaN,Boardroom Appointments - Global Human and Tale...,"['sql', 'python', 'azure', 'databricks', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
12410,784940,Data Engineer,Data Engineer,South Africa,via LinkedIn,Full-time,False,South Africa,2023-01-26 07:02:30,True,False,South Africa,None,NaN,NaN,the 42 company,"['python', 'bash', 'splunk', 'github']","{'analyst_tools': ['splunk'], 'other': ['githu..."
12411,784975,Business Analyst,Business Market Analyst,South Africa,via BeBee South Africa,Full-time,False,South Africa,2023-01-31 06:24:39,False,False,South Africa,None,NaN,NaN,ASTI Mobile Robotics,"['sap', 'power bi', 'flow']","{'analyst_tools': ['sap', 'power bi'], 'other'..."
12412,785406,Business Analyst,Sales Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Unique Personnel,"['sap', 'excel', 'git']","{'analyst_tools': ['sap', 'excel'], 'other': [..."
12413,785661,Software Engineer,Product Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Kurtosys,"['jira', 'confluence']","{'async': ['jira', 'confluence']}"

# Set Index Method

In [16]:
df_usa.set_index('job_index', inplace=True)

df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
138,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,None,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ..."
256,Data Analyst,Data Analyst,"Cape Town, South Africa",via Indeed,Full-time,False,South Africa,2023-09-06 13:08:51,True,False,South Africa,None,NaN,NaN,Mass Staffing Projects,['sql'],{'programming': ['sql']}
354,Cloud Engineer,Server Engineer,"Cape Town, South Africa",via LinkedIn,Full-time,False,South Africa,2023-09-22 13:43:18,False,False,South Africa,None,NaN,NaN,First Quantum Minerals,['azure'],{'cloud': ['azure']}
365,Data Scientist,Head of Data Science at Hire Resolve,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-01-21 13:32:58,False,False,South Africa,None,NaN,NaN,Hire Resolve,['c'],{'programming': ['c']}
423,Data Engineer,Data Engineer - Software Development Industry ...,"Cape Town, South Africa (+1 other)",via Pnet,Full-time,False,South Africa,2023-12-01 13:19:05,False,False,South Africa,None,NaN,NaN,Talent Candey,"['sql', 'aws', 'databricks', 'azure', 'hadoop'...","{'analyst_tools': ['ssis'], 'cloud': ['aws', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784842,Data Analyst,Business Data Analyst,South Africa,via LinkedIn,Contractor,False,South Africa,2023-01-17 07:02:38,False,False,South Africa,None,NaN,NaN,Boardroom Appointments - Global Human and Tale...,"['sql', 'python', 'azure', 'databricks', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
784940,Data Engineer,Data Engineer,South Africa,via LinkedIn,Full-time,False,South Africa,2023-01-26 07:02:30,True,False,South Africa,None,NaN,NaN,the 42 company,"['python', 'bash', 'splunk', 'github']","{'analyst_tools': ['splunk'], 'other': ['githu..."
784975,Business Analyst,Business Market Analyst,South Africa,via BeBee South Africa,Full-time,False,South Africa,2023-01-31 06:24:39,False,False,South Africa,None,NaN,NaN,ASTI Mobile Robotics,"['sap', 'power bi', 'flow']","{'analyst_tools': ['sap', 'power bi'], 'other'..."
785406,Business Analyst,Sales Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Unique Personnel,"['sap', 'excel', 'git']","{'analyst_tools': ['sap', 'excel'], 'other': [..."
785661,Software Engineer,Product Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Kurtosys,"['jira', 'confluence']","{'async': ['jira', 'confluence']}"

# Sort Index Method

In [18]:
#Use the sort index in pivot tables or other functions
median_pivot = df_usa.pivot_table(values='salary_year_avg', index='job_title_short',aggfunc=['median','min','max'])

median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                 87050.00         44100.0        130000.0
Data Analyst                     72183.75         44100.0        165000.0
Data Engineer                   131580.00         44100.0        249000.0
Data Scientist                   86285.00         44100.0        170500.0
Machine Learning Engineer        69300.00         44100.0        185500.0
Senior Data Analyst              69300.00         69300.0        111175.0
Senior Data Engineer            147500.00        147500.0        147500.0
Senior Data Scientist           171121.00        157500.0        890000.0

In [21]:
median_pivot.sort_values(by=('median','salary_year_avg') ,ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist           171121.00        157500.0        890000.0
Senior Data Engineer            147500.00        147500.0        147500.0
Data Engineer                   131580.00         44100.0        249000.0
Business Analyst                 87050.00         44100.0        130000.0
Data Scientist                   86285.00         44100.0        170500.0
Data Analyst                     72183.75         44100.0        165000.0
Senior Data Analyst              69300.00         69300.0        111175.0
Machine Learning Engineer        69300.00         44100.0        185500.0

In [22]:
median_pivot.sort_index(inplace=True)

median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                 87050.00         44100.0        130000.0
Data Analyst                     72183.75         44100.0        165000.0
Data Engineer                   131580.00         44100.0        249000.0
Data Scientist                   86285.00         44100.0        170500.0
Machine Learning Engineer        69300.00         44100.0        185500.0
Senior Data Analyst              69300.00         69300.0        111175.0
Senior Data Engineer            147500.00        147500.0        147500.0
Senior Data Scientist           171121.00        157500.0        890000.0