In [1]:
from tqdm.notebook import trange, tqdm
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [2]:
df_SA = df[df['job_country'] == 'South Africa'].copy()

In [3]:
df_SA

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
138,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,None,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ..."
256,Data Analyst,Data Analyst,"Cape Town, South Africa",via Indeed,Full-time,False,South Africa,2023-09-06 13:08:51,True,False,South Africa,None,NaN,NaN,Mass Staffing Projects,['sql'],{'programming': ['sql']}
354,Cloud Engineer,Server Engineer,"Cape Town, South Africa",via LinkedIn,Full-time,False,South Africa,2023-09-22 13:43:18,False,False,South Africa,None,NaN,NaN,First Quantum Minerals,['azure'],{'cloud': ['azure']}
365,Data Scientist,Head of Data Science at Hire Resolve,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-01-21 13:32:58,False,False,South Africa,None,NaN,NaN,Hire Resolve,['c'],{'programming': ['c']}
423,Data Engineer,Data Engineer - Software Development Industry ...,"Cape Town, South Africa (+1 other)",via Pnet,Full-time,False,South Africa,2023-12-01 13:19:05,False,False,South Africa,None,NaN,NaN,Talent Candey,"['sql', 'aws', 'databricks', 'azure', 'hadoop'...","{'analyst_tools': ['ssis'], 'cloud': ['aws', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784842,Data Analyst,Business Data Analyst,South Africa,via LinkedIn,Contractor,False,South Africa,2023-01-17 07:02:38,False,False,South Africa,None,NaN,NaN,Boardroom Appointments - Global Human and Tale...,"['sql', 'python', 'azure', 'databricks', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
784940,Data Engineer,Data Engineer,South Africa,via LinkedIn,Full-time,False,South Africa,2023-01-26 07:02:30,True,False,South Africa,None,NaN,NaN,the 42 company,"['python', 'bash', 'splunk', 'github']","{'analyst_tools': ['splunk'], 'other': ['githu..."
784975,Business Analyst,Business Market Analyst,South Africa,via BeBee South Africa,Full-time,False,South Africa,2023-01-31 06:24:39,False,False,South Africa,None,NaN,NaN,ASTI Mobile Robotics,"['sap', 'power bi', 'flow']","{'analyst_tools': ['sap', 'power bi'], 'other'..."
785406,Business Analyst,Sales Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Unique Personnel,"['sap', 'excel', 'git']","{'analyst_tools': ['sap', 'excel'], 'other': [..."
785661,Software Engineer,Product Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Kurtosys,"['jira', 'confluence']","{'async': ['jira', 'confluence']}"

In [4]:
#Get the full month name of when the jobs were posted
df_SA['job_posted_month'] = df_SA['job_posted_date'].dt.strftime('%B')

df_SA

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
138,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,None,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ...",February
256,Data Analyst,Data Analyst,"Cape Town, South Africa",via Indeed,Full-time,False,South Africa,2023-09-06 13:08:51,True,False,South Africa,None,NaN,NaN,Mass Staffing Projects,['sql'],{'programming': ['sql']},September
354,Cloud Engineer,Server Engineer,"Cape Town, South Africa",via LinkedIn,Full-time,False,South Africa,2023-09-22 13:43:18,False,False,South Africa,None,NaN,NaN,First Quantum Minerals,['azure'],{'cloud': ['azure']},September
365,Data Scientist,Head of Data Science at Hire Resolve,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-01-21 13:32:58,False,False,South Africa,None,NaN,NaN,Hire Resolve,['c'],{'programming': ['c']},January
423,Data Engineer,Data Engineer - Software Development Industry ...,"Cape Town, South Africa (+1 other)",via Pnet,Full-time,False,South Africa,2023-12-01 13:19:05,False,False,South Africa,None,NaN,NaN,Talent Candey,"['sql', 'aws', 'databricks', 'azure', 'hadoop'...","{'analyst_tools': ['ssis'], 'cloud': ['aws', '...",December
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784842,Data Analyst,Business Data Analyst,South Africa,via LinkedIn,Contractor,False,South Africa,2023-01-17 07:02:38,False,False,South Africa,None,NaN,NaN,Boardroom Appointments - Global Human and Tale...,"['sql', 'python', 'azure', 'databricks', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['azure'...",January
784940,Data Engineer,Data Engineer,South Africa,via LinkedIn,Full-time,False,South Africa,2023-01-26 07:02:30,True,False,South Africa,None,NaN,NaN,the 42 company,"['python', 'bash', 'splunk', 'github']","{'analyst_tools': ['splunk'], 'other': ['githu...",January
784975,Business Analyst,Business Market Analyst,South Africa,via BeBee South Africa,Full-time,False,South Africa,2023-01-31 06:24:39,False,False,South Africa,None,NaN,NaN,ASTI Mobile Robotics,"['sap', 'power bi', 'flow']","{'analyst_tools': ['sap', 'power bi'], 'other'...",January
785406,Business Analyst,Sales Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Unique Personnel,"['sap', 'excel', 'git']","{'analyst_tools': ['sap', 'excel'], 'other': [...",August
785661,Software Engineer,Product Analyst,South Africa,via Trabajo.org,Full-time,False,South Africa,2023-08-17 06:52:32,True,False,South Africa,None,NaN,NaN,Kurtosys,"['jira', 'confluence']","{'async': ['jira', 'confluence']}",August